run:
  issues-exit-code: 1

linters:
  enable-all: true
  disable:
    - maligned
    - prealloc
    - lll
    - gochecknoglobals
    - unparam
    - goconst
    - exhaustivestruct
    - wrapcheck
linters-settings:
  govert:
    check-shadowing: true