version: '3.3'

services:
  movieservice:
    container_name: movieservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      MOVIESERVICE_SERVE_REST_ADDRESS: ":8000"
      MOVIESERVICE_MYSQL_DATABASE: "movie"
      MOVIESERVICE_MYSQL_USER: "root"
      MOVIESERVICE_MYSQL_PASSWORD: "12345678"
      MOVIESERVICE_MYSQL_ADDRESS: "tcp(movieservice-db:3306)"
    depends_on:
      movieservice-db:
        condition: service_healthy

  movieservice-db:
    image: "mysql:8.0"
    container_name: movieservice-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "movie"
      MYSQL_ROOT_PASSWORD: "12345678"
    healthcheck:
      test: mysql -uroot -p12345678 -e 'SELECT 1'
      interval: 20s
      timeout: 1s
    volumes:
      - "db-data:/var/lib/mysql"
volumes:
  db-data: