run:
  issues-exit-code: 1

linters:
  enable-all: true
  disable:
    - maligned
    - prealloc
linters-settings:
  govert:
    check-shadowing: true
  goimports:
    local-prefixes: compiler