version: '3.3'

services:
  cinema:
    container_name: cinema
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      CINEMA_SERVE_REST_ADDRESS: ":8000"
      CINEMA_MYSQL_DATABASE: "cinema"
      CINEMA_MYSQL_USER: "root"
      CINEMA_MYSQL_PASSWORD: "12345678"
    depends_on:
      - cinema-db

  cinema-db:
    image: "mysql:8.0"
    container_name: cinema-db
    environment:
      MYSQL_DATABASE: cinema
      MYSQL_ROOT_PASSWORD: 12345678
volumes:
  db-data: